# Generated by Django 5.2.7 on 2025-10-04 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('hero_image', models.CharField(blank=True, max_length=255)),
                ('color_primary', models.CharField(default='#5b1fa6', max_length=7)),
                ('color_secondary', models.CharField(default='#311b92', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='accommodations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='action1_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='action1_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='action2_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='action2_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='action3_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='action3_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_friend_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_friend_of_friend_invites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends'), ('extended_friends', 'Friends of friends'), ('group', 'Group members'), ('custom', 'Selected friends')], default='everyone', max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='available_responses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='color_primary',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='activity',
            name='color_secondary',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='activity',
            name='cost_display',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='cost_has_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='freetext_when',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='activity',
            name='header_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_personal_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_gps',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_type',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('tbd', 'TBD')], default='tbd', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='multiple_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='activity',
            name='post_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.CreateModel(
            name='ActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('committed', 'Count me in'), ('question', 'I have a question'), ('declined', 'Cannot make it')], default='interested', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
