# Generated by Django 5.2.7 on 2025-10-09 00:21

import mimetypes
from pathlib import Path

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def import_activity_images(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    ImageAsset = apps.get_model("media_assets", "ImageAsset")

    base_static = Path(settings.BASE_DIR, "static")

    for activity in Activity.objects.all().iterator():
        organizer_path = getattr(activity, "organizer_image", "")
        header_path = getattr(activity, "header_image", "")

        changed = False

        if organizer_path:
            organizer_asset = _ensure_asset(
                ImageAsset,
                base_static,
                organizer_path,
                purpose="organizer",
                name=f"{activity.title} organizer",
            )
            if organizer_asset:
                activity.organizer_image_asset = organizer_asset
                changed = True

        if header_path:
            header_asset = _ensure_asset(
                ImageAsset,
                base_static,
                header_path,
                purpose="activity_header",
                name=f"{activity.title} header",
            )
            if header_asset:
                activity.header_image_asset = header_asset
                changed = True

        if changed:
            activity.save(update_fields=["organizer_image_asset", "header_image_asset"])


def _ensure_asset(ImageAsset, base_static: Path, legacy_path: str, *, purpose: str, name: str):
    asset_path = base_static / legacy_path
    if not asset_path.exists():
        return None

    payload = asset_path.read_bytes()
    content_type = mimetypes.guess_type(asset_path.name)[0] or "application/octet-stream"
    asset, _ = ImageAsset.objects.get_or_create(
        purpose=purpose,
        filename=legacy_path,
        defaults={
            "name": name,
            "data": payload,
            "content_type": content_type,
            "size": len(payload),
        },
    )
    return asset


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitycategory_remove_activity_location_and_more'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='header_image_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'activity_header'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_activities', to='media_assets.imageasset'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer_image_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'organizer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_activities', to='media_assets.imageasset'),
        ),
        migrations.RunPython(import_activity_images, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='activity',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='organizer_image',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='header_image_asset',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='organizer_image_asset',
            new_name='organizer_image',
        ),
    ]
