# Generated by Django 5.2.7 on 2026-10-04 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_demo_seed_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action1_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action2_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action3_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
