# Generated by Django 5.2.7 on 2026-10-04 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_validate_action_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('free', 'Free'), ('paid', 'Paid')], default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='activityresponse',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('committed', 'Count me in'), ('question', 'I have a question'), ('declined', 'Cannot make it'), ('more', 'Tell me more'), ('vote', 'Vote on details')], default='interested', max_length=20),
        ),
        migrations.CreateModel(
            name='HiddenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_preferences', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'activity'), name='unique_hidden_activity')],
            },
        ),
    ]
