# Generated by Django 5.2.7 on 2026-10-05 03:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_reconcile_demo_sample_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount per person in USD. Leave blank if not yet known.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
