# Generated by Django 5.2.7 on 2026-10-06 15:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_hiddenorganizer'),
        ('groups', '0004_group_default_activity_image_group_image'),
        ('media_assets', '0002_alter_imageasset_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends'), ('extended_friends', 'Friends of friends')], default='everyone', max_length=40)),
                ('available_responses', models.JSONField(blank=True, default=list)),
                ('location_type', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('tbd', 'TBD')], default='tbd', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_address1', models.CharField(blank=True, max_length=200)),
                ('location_address2', models.CharField(blank=True, max_length=200)),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('location_state', models.CharField(blank=True, max_length=120)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('location_url', models.URLField(blank=True)),
                ('location_gps', models.CharField(blank=True, max_length=120)),
                ('location_instructions', models.TextField(blank=True)),
                ('cost_type', models.CharField(choices=[('unknown', 'Unknown'), ('free', 'Free'), ('paid', 'Paid')], default='unknown', max_length=12)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_display', models.CharField(blank=True, max_length=120)),
                ('color_primary', models.CharField(blank=True, max_length=7)),
                ('color_secondary', models.CharField(blank=True, max_length=7)),
                ('cadence', models.CharField(choices=[('flexible', 'As arranged'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='flexible', max_length=12)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('usual_start_time', models.TimeField(blank=True, null=True)),
                ('cadence_description', models.CharField(blank=True, help_text='Optional schedule details, such as the first Saturday of each month.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='activities.activitycategory')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='groups.group')),
                ('header_image', models.ForeignKey(blank=True, limit_choices_to={'purpose': 'activity_header'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_series', to='media_assets.imageasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='activities.activityseries'),
        ),
        migrations.AddConstraint(
            model_name='activityseries',
            constraint=models.CheckConstraint(condition=models.Q(('cadence__in', ['flexible', 'daily', 'weekly', 'monthly'])), name='series_valid_cadence'),
        ),
        migrations.AddConstraint(
            model_name='activityseries',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__isnull', True), ('weekday__lte', 6), _connector='OR'), name='series_valid_weekday'),
        ),
    ]
