# Generated by Django 5.2.7 on 2026-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_activity_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends'), ('extended_friends', 'Friends of friends')], default='everyone', max_length=40),
        ),
    ]
