# Generated by Django 5.2.7 on 2026-10-06 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_alter_activity_audience'),
        ('groups', '0005_group_interests'),
        ('media_assets', '0002_alter_imageasset_purpose'),
        ('social', '0008_seed_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cancellation_reason',
            field=models.TextField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_default='active', default='active', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'cancelled'])), name='activity_valid_status'),
        ),
    ]
