# Generated by Django 5.2.7 on 2026-10-07 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='invite_group_members',
            field=models.BooleanField(default=False, verbose_name='Invite active group members'),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='invite_group_members',
            field=models.BooleanField(default=False, verbose_name='Invite active group members'),
        ),
        migrations.CreateModel(
            name='ActivityInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_invitations', to='activities.activity')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_activity_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_invitee')],
            },
        ),
    ]
