# Generated by Django 5.2.7 on 2026-10-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_activityemailinvitation'),
        ('groups', '0005_group_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('accepted', 'Accepted')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_join_offers', to='activities.activity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_join_offers', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='unique_activity_group_join_offer'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'dismissed', 'accepted'])), name='activity_group_offer_valid_status')],
            },
        ),
    ]
