# Generated by Django 5.2.7 on 2026-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_groupjoinoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityresponse',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested (historical)'), ('committed', 'Count me in'), ('question', 'I have a question'), ('declined', 'Cannot make it'), ('more', 'Tell me more'), ('vote', 'Vote on details')], default='more', max_length=20),
        ),
    ]
