# Generated by Django 5.2.7 on 2026-10-08 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_alter_activityresponse_status'),
        ('social', '0012_userprofile_activity_email_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('update', 'Update'), ('cancellation', 'Cancellation')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='activities.activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_hash', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unknown', 'Unknown')], default='pending', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.outboundemailattempt')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='activities.activitynotificationevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='activitynotificationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'cancellation')), fields=('activity',), name='one_activity_cancellation_notification'),
        ),
        migrations.AddConstraint(
            model_name='activitynotificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'channel'), name='unique_activity_notification_delivery'),
        ),
    ]
