# Generated by Django 5.2.7 on 2026-10-08 18:50

import activities.participation_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_announcement_submission_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participation_config',
            field=models.JSONField(blank=True, default=None, null=True, validators=[activities.participation_config.validate_config]),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='participation_config',
            field=models.JSONField(blank=True, default=None, null=True, validators=[activities.participation_config.validate_config]),
        ),
    ]
