# Generated by Django 5.2.7 on 2026-10-08 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_activity_participation_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotificationevent',
            name='kind',
            field=models.CharField(choices=[('update', 'Update'), ('cancellation', 'Cancellation'), ('confirmation', 'Confirm attendance')], max_length=12),
        ),
        migrations.CreateModel(
            name='ConfirmationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prior_schedule', models.JSONField(default=dict)),
                ('finalized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activitynotificationevent',
            name='confirmation_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activities.confirmationround'),
        ),
        migrations.CreateModel(
            name='DatePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_poll', to='activities.activity')),
            ],
        ),
        migrations.AddField(
            model_name='confirmationround',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='activities.datepoll'),
        ),
        migrations.CreateModel(
            name='DatePollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='activities.datepoll')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='confirmationround',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.datepolloption'),
        ),
        migrations.CreateModel(
            name='DatePollSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.datepoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='activities.confirmationround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'user'), name='unique_round_confirmation_invitation')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('committed', 'Going'), ('declined', "Can't make it"), ('withdrawn', 'Withdrawn')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='activities.confirmationround')),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['round', 'user', 'id'], name='round_user_attendance')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['committed', 'declined', 'withdrawn'])), name='round_attendance_valid_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='datepolloption',
            constraint=models.UniqueConstraint(fields=('poll', 'position'), name='unique_date_poll_position'),
        ),
        migrations.AddConstraint(
            model_name='datepolloption',
            constraint=models.UniqueConstraint(fields=('poll', 'starts_at'), name='unique_date_poll_date'),
        ),
        migrations.AddConstraint(
            model_name='datepolloption',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='date_poll_three_positions'),
        ),
        migrations.AddIndex(
            model_name='datepollsubmission',
            index=models.Index(fields=['poll', 'user', 'id'], name='poll_user_submission'),
        ),
    ]
