# Generated by Django 5.2.7 on 2026-10-08 20:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_alter_activitynotificationevent_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OngoingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='activities.enrollmentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CohortPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='activities.ongoingenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('policy', models.CharField(default='approval_secures_place', editable=False, max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing', to='activities.activity')),
            ],
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='activities.ongoingopportunity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='ongoing_opportunity',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='activities.ongoingopportunity'),
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='activities.enrollmentrequest')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('result__in', ['approved', 'denied'])), name='valid_enrollment_decision')],
            },
        ),
        migrations.AddConstraint(
            model_name='ongoingopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('policy', 'approval_secures_place'), ('version', 1)), name='ongoing_free_approval_policy'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('opportunity', 'user'), name='unique_open_enrollment_request'),
        ),
    ]
