# Generated by Django 5.2.7 on 2026-10-08 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_enrollmentrequest_ongoingenrollment_cohortplace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='place', to='activities.freeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='freeregistration',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='activities.registrationrequest'),
        ),
        migrations.CreateModel(
            name='RegistrationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('admission', models.CharField(choices=[('open', 'Open'), ('request', 'Request required'), ('invitation', 'Invitation required')], max_length=10)),
                ('allocation', models.CharField(choices=[('claim', 'Eligibility only; place confirmation is separate'), ('approval', 'Approval secures a free place')], max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration_target', to='activities.activity')),
            ],
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='activities.registrationtarget'),
        ),
        migrations.CreateModel(
            name='RegistrationAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='activities.registrationrequest')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('result__in', ['approved', 'denied'])), name='registration_decision_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationtarget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('currency', 'USD'), ('version', 1)), name='registration_quote_valid'),
        ),
        migrations.AddConstraint(
            model_name='registrationtarget',
            constraint=models.CheckConstraint(condition=models.Q(('admission__in', ['open', 'request', 'invitation'])), name='registration_admission_valid'),
        ),
        migrations.AddConstraint(
            model_name='registrationtarget',
            constraint=models.CheckConstraint(condition=models.Q(('allocation', 'claim'), models.Q(('admission', 'request'), ('allocation', 'approval'), ('amount', 0)), _connector='OR'), name='registration_allocation_valid'),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('target', 'user'), name='unique_open_registration'),
        ),
    ]
