# Generated by Django 5.2.7 on 2026-10-08 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_freeregistration_registrationplace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotificationevent',
            name='kind',
            field=models.CharField(choices=[('update', 'Update'), ('cancellation', 'Cancellation'), ('confirmation', 'Confirm attendance'), ('place_offer', 'Free place offer')], max_length=12),
        ),
        migrations.CreateModel(
            name='FreeReservationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('ineligible', 'No longer eligible'), ('cancelled', 'Cancelled')], max_length=16)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_holds', to='activities.registrationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='activitynotificationevent',
            name='reservation_hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activities.freereservationhold'),
        ),
        migrations.CreateModel(
            name='FreeReservationPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('waitlist_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_pool', to='activities.registrationtarget')),
            ],
        ),
        migrations.AddField(
            model_name='freereservationhold',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='activities.freereservationpool'),
        ),
        migrations.CreateModel(
            name='FreePoolCapacityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('previous', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_changes', to='activities.freereservationpool')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FreeWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('ineligible', 'No longer eligible'), ('cancelled', 'Cancelled')], max_length=16)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='activities.freereservationpool')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='activities.registrationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='freereservationhold',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='activities.freewaitlistentry'),
        ),
        migrations.AddConstraint(
            model_name='freereservationpool',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('revision__gte', 1)), name='free_pool_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='freepoolcapacitychange',
            constraint=models.UniqueConstraint(fields=('pool', 'revision'), name='unique_free_pool_revision'),
        ),
        migrations.AddConstraint(
            model_name='freewaitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('pool', 'user'), name='one_active_free_queue_entry'),
        ),
        migrations.AddConstraint(
            model_name='freereservationhold',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('pool', 'user'), name='one_active_free_hold'),
        ),
        migrations.AddConstraint(
            model_name='freereservationhold',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='free_hold_positive_duration'),
        ),
    ]
