"""
Django settings for belong project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from .environment import config_bool, read_local_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Process environment takes precedence over this checkout's ignored local file.
try:
    CONFIG = read_local_config(BASE_DIR / '.env.local') | os.environ
except ValueError as error:
    raise ImproperlyConfigured(str(error)) from error
ENVIRONMENT = CONFIG.get('BELONG_ENV', 'dev')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONFIG.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    try:
        SECRET_KEY = (BASE_DIR / '.django-secret-key').read_text().strip()
    except FileNotFoundError:
        pass
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'Set DJANGO_SECRET_KEY or create .django-secret-key as described in README.md.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
try:
    DEBUG = config_bool(CONFIG.get('DJANGO_DEBUG', str(ENVIRONMENT in {'dev', 'test'})))
except ValueError as error:
    raise ImproperlyConfigured(str(error)) from error

ALLOWED_HOSTS = [
    host.strip()
    for host in CONFIG.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')
    if host.strip()
]

# Browsers share cookies between ports on the same host.
SESSION_COOKIE_NAME = f'belong_{ENVIRONMENT}_sessionid'
CSRF_COOKIE_NAME = f'belong_{ENVIRONMENT}_csrftoken'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'activities',
    'social.apps.SocialConfig',
    'groups.apps.GroupsConfig',
    'media_assets.apps.MediaAssetsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social.middleware.ActivityPresenceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'belong.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'belong.context_processors.card_layout',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'belong.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': (BASE_DIR / Path(CONFIG.get('DJANGO_DB_PATH', 'db.sqlite3')).expanduser()).resolve(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Pilot dates and datetime-local forms use Eastern time, including DST.
TIME_ZONE = 'America/New_York'
PILOT_TIME_ZONE = TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'activities:index'
LOGOUT_REDIRECT_URL = 'activities:index'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CARD_HEIGHT = 400            # example height in px
CARD_WIDTH_RATIO = 0.645      # width = height * ratio
CARD_BANDS = [0.20, 0.12, 0.24, 0.16, 0.28]

STACK_OFFSET = round(CARD_HEIGHT * sum(CARD_BANDS[:2]))
BASE_FONT = round(CARD_HEIGHT * 0.04)   # ≈4% of height
CARD_MIN_WIDTH = round(CARD_HEIGHT * CARD_WIDTH_RATIO)



CARD_LAYOUT = {
    "height": CARD_HEIGHT,
    "width_ratio": CARD_WIDTH_RATIO,
    "bands": CARD_BANDS,
    "stack_offset": STACK_OFFSET,
    "base_font": BASE_FONT,
    "min_width": CARD_MIN_WIDTH,
    "max_stack_size": 3,
    "max_stack_columns": 5,
}
