# Generated by Django 5.2.7 on 2025-10-09 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('purpose', models.CharField(choices=[('generic', 'Generic'), ('profile_avatar', 'Profile avatar'), ('organizer', 'Activity organizer'), ('activity_header', 'Activity header')], default='generic', help_text='Used to filter image choices in forms.', max_length=40)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField()),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
