# Generated by Django 5.2.7 on 2026-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='purpose',
            field=models.CharField(choices=[('generic', 'Generic'), ('profile_avatar', 'Profile avatar'), ('organizer', 'Activity organizer'), ('group_image', 'Group image'), ('activity_header', 'Activity header')], default='generic', help_text='Used to filter image choices in forms.', max_length=40),
        ),
    ]
