# Generated by Django 5.2.7 on 2026-10-04 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public — visible through linked activities'), ('unlisted', 'Unlisted — accessible by direct link'), ('private', 'Private — members only')], default='public', max_length=12)),
                ('join_policy', models.CharField(choices=[('open', 'Anyone can join'), ('approval', 'Organizer approval required'), ('invite', 'Invitation only')], default='approval', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('organizer', 'Organizer')], default='member', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Awaiting approval')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'unlisted', 'private'])), name='group_valid_visibility'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('join_policy__in', ['open', 'approval', 'invite'])), name='group_valid_join_policy'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_member'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['member', 'organizer'])), name='group_member_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'pending'])), name='group_member_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'organizer'), _negated=True), ('status', 'active'), _connector='OR'), name='group_organizer_active'),
        ),
    ]
