# Generated by Django 5.2.7 on 2026-10-04 23:08

from django.conf import settings
from django.db import migrations, models


def migrate_access(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    for group in Group.objects.using(schema_editor.connection.alias).all().iterator():
        # Keep hidden groups hidden. Legacy public invitation-only groups become
        # Private rather than granting self-join access. Unlisted now joins openly
        # as explicitly decided in #21; preserve all membership rows unchanged.
        if group.visibility == 'private':
            access = 'private'
        elif group.visibility == 'unlisted':
            access = 'unlisted'
        elif group.join_policy == 'invite':
            access = 'private'
        elif group.join_policy == 'open':
            access = 'open'
        else:
            access = 'closed'
        Group.objects.using(schema_editor.connection.alias).filter(pk=group.pk).update(access=access)


def restore_axes(apps, schema_editor):
    Group = apps.get_model('groups', 'Group')
    mapping = {'open': ('public', 'open'), 'closed': ('public', 'approval'),
               'unlisted': ('unlisted', 'open'), 'private': ('private', 'invite')}
    for access, (visibility, join_policy) in mapping.items():
        Group.objects.using(schema_editor.connection.alias).filter(access=access).update(visibility=visibility, join_policy=join_policy)
    # The old schema cannot express blocked membership; refuse a downgrade that
    # could silently grant access to a blocked user.
    if apps.get_model('groups', 'GroupMembership').objects.using(schema_editor.connection.alias).filter(status='blocked').exists():
        raise RuntimeError('Cannot reverse access modes while blocked memberships exist.')


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='access',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='closed', max_length=12),
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='group_valid_visibility',
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='group_valid_join_policy',
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='group_member_valid_status',
        ),
        migrations.RunPython(migrate_access, restore_axes),
        migrations.RemoveField(
            model_name='group',
            name='join_policy',
        ),
        migrations.RemoveField(
            model_name='group',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Awaiting approval'), ('blocked', 'Blocked')], default='active', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('access__in', ['open', 'closed', 'unlisted', 'private'])), name='group_valid_access'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'pending', 'blocked'])), name='group_member_valid_status'),
        ),
    ]
