# Generated by Django 5.2.7 on 2026-10-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupinvitation'),
        ('media_assets', '0002_alter_imageasset_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_activity_image',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'activity_header'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_activity_groups', to='media_assets.imageasset'),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'group_image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_images', to='media_assets.imageasset'),
        ),
    ]
