# Generated by Django 5.2.7 on 2026-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_default_activity_image_group_image'),
        ('social', '0007_interest_userprofile_interests_prompt_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='groups', to='social.interest'),
        ),
    ]
