# Generated by Django 5.2.7 on 2025-10-09 00:21

import mimetypes
from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def import_avatar_images(apps, schema_editor):
    ImageAsset = apps.get_model("media_assets", "ImageAsset")
    UserProfile = apps.get_model("social", "UserProfile")

    base_static = Path(settings.BASE_DIR, "static")

    for profile in UserProfile.objects.all().iterator():
        legacy_path = getattr(profile, "avatar_image", "")
        if not legacy_path:
            continue

        asset_path = base_static / legacy_path
        if not asset_path.exists():
            continue

        payload = asset_path.read_bytes()
        content_type = mimetypes.guess_type(asset_path.name)[0] or "application/octet-stream"
        asset, _ = ImageAsset.objects.get_or_create(
            purpose="profile_avatar",
            filename=legacy_path,
            defaults={
                "name": f"{profile.user_id} avatar",
                "data": payload,
                "content_type": content_type,
                "size": len(payload),
            },
        )
        profile.avatar_image_asset = asset
        profile.save(update_fields=["avatar_image_asset"])


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'profile_avatar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='media_assets.imageasset'),
        ),
        migrations.RunPython(import_avatar_images, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar_image_asset',
            new_name='avatar_image',
        ),
    ]
