# Generated by Django 5.2.7 on 2026-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_convert_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
