# Generated by Django 5.2.7 on 2026-10-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_scrub_invitation_session_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('section', 'name'),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests_prompt_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='social.interest'),
        ),
        migrations.CreateModel(
            name='InterestSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_suggestions', to='social.userprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
