# Generated by Django 5.2.7 on 2026-10-06 19:50

import hashlib
from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_lock(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('social', 'EmailControlLock').objects.using(alias).get_or_create(pk=1)
    Attempt = apps.get_model('social', 'OutboundEmailAttempt')
    digest = lambda value: hashlib.sha256(value.strip().lower().encode()).hexdigest()
    # Existing persisted proofs/invitations represent successful delivery in the
    # old transaction-based sender. Preserve their recent address/actor cooldowns.
    for proof in apps.get_model('social', 'EmailVerification').objects.using(alias).iterator():
        Attempt.objects.using(alias).create(kind='verification', actor_id=proof.user_id,
            recipient_hash=digest(proof.email), ip_hash=digest('unknown'),
            created_at=proof.created_at, outcome='sent', reason='migration_backfill')
    for invitation in apps.get_model('groups', 'GroupInvitation').objects.using(alias).iterator():
        Attempt.objects.using(alias).create(kind='invitation', actor_id=invitation.inviter_id,
            recipient_hash=digest(invitation.email), ip_hash=digest('unknown'),
            group_reference=invitation.group_id, created_at=invitation.expires_at-timedelta(days=7),
            outcome='sent', reason='migration_backfill')


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_seed_interests'),
        ('groups', '0005_group_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailControlLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('touched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outbound_mail_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountEmailProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(max_length=16)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=24)),
                ('recipient_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('group_reference', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('outcome', models.CharField(default='reserved', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(seed_lock, migrations.RunPython.noop),
    ]
