# Generated by Django 5.2.7 on 2026-10-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_emailcontrollock_userprofile_outbound_mail_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='outbound_mail_suspended',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
