# Generated by Django 5.2.7 on 2026-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_userprofile_outbound_mail_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemailattempt',
            name='activity_reference',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
