# Generated by Django 5.2.7 on 2026-10-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_outboundemailattempt_activity_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
